[pyprland]
plugins = ["scratchpads", "magnify", "layout_center"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"
margin = 50
unfocus = "hide"
max_size = "1920px 100%"

[scratchpads.volume]
command = "pavucontrol"
animation = "fromRight"
class = "pavucontrol"
unfocus = "hide"
lazy = true
size = "40% 90%"

[layout_center]
margin = 60
offset = [0, 30]
next = "movefocus r"
prev = "movefocus l"
next2 = "movefocus d"
prev2 = "movefocus u"
